import { createContext, useContext } from "react";

export const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const translations = {
  vi: {
    // Sidebar
    home: "Trang chủ",
    discover: "Khám phá",
    connections: "Kết nối",
    messages: "Tin nhắn",
    projects: "Dự án",
    aiChat: "Chat AI",
    profile: "Hồ sơ",
    createPost: "Tạo bài viết",
    logout: "Đăng xuất",

    // Feed
    whatsHappening: "Có gì mới?",
    posts: "Bài viết",
    shares: "Chia sẻ",
    media: "Phương tiện",
    likes: "Thích",

    // Post actions
    like: "Thích",
    comment: "Bình luận",
    share: "Chia sẻ",
    sharePost: "Chia sẻ bài viết",
    shareToProfile: "Chia sẻ lên trang cá nhân",
    addComment: "Thêm bình luận...",
    writeComment: "Viết bình luận...",
    noComments: "Chưa có bình luận",
    loadingComments: "Đang tải bình luận...",
    commentAdded: "Đã thêm bình luận",
    commentDeleted: "Đã xóa bình luận",

    // Post management
    edit: "Chỉnh sửa",
    delete: "Xóa",
    deletePost: "Xóa bài viết",
    editPost: "Chỉnh sửa bài viết",
    deleting: "Đang xóa...",
    saving: "Đang lưu...",
    saveChanges: "Lưu thay đổi",
    cancel: "Hủy",
    postDeleted: "Đã xóa bài viết",
    postUpdated: "Đã cập nhật bài viết",
    confirmDeletePost: "Bạn có chắc muốn xóa bài viết này?",
    contentRequired: "Nội dung không được để trống",

    // Story
    createStory: "Tạo Story",
    deleteStory: "Xóa Story",
    storyDeleted: "Đã xóa story",
    confirmDeleteStory: "Bạn có chắc muốn xóa story này?",
    text: "Văn bản",
    photoVideo: "Ảnh/Video",

    // Connections
    followers: "Người theo dõi",
    following: "Đang theo dõi",
    pending: "Chờ xác nhận",
    connectionsLabel: "Kết nối",
    follow: "Theo dõi",
    unfollow: "Bỏ theo dõi",
    accept: "Chấp nhận",
    viewProfile: "Xem hồ sơ",
    message: "Nhắn tin",
    manageNetwork: "Quản lý mạng lưới và khám phá kết nối mới",

    // Discover
    discoverPeople: "Khám phá mọi người",
    connectWithPeople: "Kết nối với những người tuyệt vời và mở rộng mạng lưới",
    searchPlaceholder: "Tìm kiếm theo tên, username, bio hoặc vị trí...",

    // Messages
    talkToFriends: "Trò chuyện với bạn bè hoặc nhóm",
    createGroup: "Tạo nhóm",
    groupName: "Tên nhóm",
    groups: "Nhóm",
    members: "thành viên",
    noGroups: "Chưa có nhóm. Hãy tạo một nhóm!",
    friends: "Bạn bè",
    typeMessage: "Nhập tin nhắn...",
    postNotAdded: "Không thể thêm bài viết",
    postAdded: "Đã thêm bài viết",
    uploading: "Đang tải lên...",
    confirmDeleteMessage: "Bạn có chắc muốn xóa tin nhắn này?",
    messageDeleted: "Đã xóa tin nhắn",

    // AI Chat
    newConversation: "Cuộc trò chuyện mới",
    noConversations: "Chưa có cuộc trò chuyện nào",
    rename: "Đổi tên",
    aiAssistant: "AI Assistant",
    chatting: "Đang trò chuyện",
    aiWelcome: "Xin chào! Tôi là AI Assistant",
    aiDescription:
      "Tôi có thể giúp bạn trả lời câu hỏi, viết nội dung, giải thích vấn đề và nhiều hơn nữa. Hãy bắt đầu cuộc trò chuyện!",
    aiDisclaimer: "AI có thể mắc lỗi. Hãy kiểm tra thông tin quan trọng.",

    // Create Post
    shareThoughts: "Chia sẻ suy nghĩ của bạn với thế giới",
    publishPost: "Đăng bài",

    // Profile
    editProfile: "Chỉnh sửa hồ sơ",
    noPosts: "Chưa có bài viết",
    noSharedPosts: "Chưa có bài viết được chia sẻ",
    joined: "Tham gia",
    addLocation: "Thêm vị trí",
    addUsername: "Thêm tên người dùng",

    // Common
    loading: "Đang tải...",
    error: "Lỗi",
    success: "Thành công",
    confirm: "Xác nhận",
    close: "Đóng",
    you: "Bạn",
    new: "Mới",
    image: "Hình ảnh",
    personal: "Cá nhân",
    noMessages: "Chưa có tin nhắn nào",
    noGroupMessages: "Chưa có tin nhắn nhóm nào",
    sponsored: "Tài trợ",
    sharedAPost: "đã chia sẻ một bài viết",
    addShareComment: "Thêm bình luận cho bài chia sẻ...",
    sharing: "Đang chia sẻ...",
    postContent: "Nội dung bài viết...",

    // Login
    loginTitle: "Kết nối thực sự, không chỉ là bạn bè",
    loginSubtitle: "Kết nối với cộng đồng toàn cầu trên PingUp.",
    usedByDevelopers: "Được sử dụng bởi 12k+ nhà phát triển",

    // Theme
    lightMode: "Chế độ sáng",
    darkMode: "Chế độ tối",

    // Language
    language: "Ngôn ngữ",
    vietnamese: "Tiếng Việt",
    english: "English",

    // Video Call
    videoCall: "Gọi video",
    audioCall: "Gọi thoại",
    groupCall: "Gọi nhóm",
    calling: "Đang gọi...",
    connecting: "Đang kết nối...",
    connected: "Đã kết nối",
    callEnded: "Cuộc gọi đã kết thúc",
    callRejected: "Cuộc gọi bị từ chối",
    callFailed: "Kết nối thất bại",
    endCall: "Kết thúc cuộc gọi",
    mute: "Tắt mic",
    unmute: "Bật mic",
    turnOnCamera: "Bật camera",
    turnOffCamera: "Tắt camera",
    shareScreen: "Chia sẻ màn hình",
    stopSharing: "Dừng chia sẻ",
    screenSharing: "Đang chia sẻ màn hình",
    waitingForOthers: "Đang chờ người khác tham gia...",
    peopleInCall: "người đang gọi",
    joinCall: "Tham gia cuộc gọi",
    incomingCall: "Cuộc gọi đến",
    acceptCall: "Chấp nhận",
    declineCall: "Từ chối",
    fullscreen: "Toàn màn hình",
    exitFullscreen: "Thoát toàn màn hình",
    clickToExpand: "Nhấn để phóng to",
    clickToClose: "Nhấn bất kỳ đâu để đóng",

    // Projects & Kanban
    projectManagement: "Quản lý dự án",
    createProject: "Tạo dự án",
    createNewProject: "Tạo dự án mới",
    projectName: "Tên dự án",
    projectNamePlaceholder: "Dự án tuyệt vời của tôi",
    projectKey: "Mã dự án",
    projectKeyExample: "VD: PROJ, DEV",
    projectKeyHint:
      "Mã này sẽ được dùng làm tiền tố cho công việc (VD: PROJ-1, PROJ-2)",
    projectDescription: "Mô tả dự án",
    projectDescPlaceholder: "Mô tả dự án của bạn...",
    projectCreatedSuccess: "Tạo dự án thành công!",
    failedToCreateProject: "Không thể tạo dự án",
    creating: "Đang tạo...",
    noConnectionsAvailable: "Chưa có kết nối. Hãy thêm bạn bè trước.",
    methodology: "Phương pháp",
    scrum: "Scrum",
    kanban: "Kanban",
    waterfall: "Waterfall",
    startDate: "Ngày bắt đầu",
    endDate: "Ngày kết thúc",
    teamMembers: "Thành viên nhóm",
    noProjects: "Chưa có dự án nào",
    viewDetails: "Xem chi tiết",
    deleteProject: "Xóa dự án",
    confirmDeleteProject: "Bạn có chắc muốn xóa dự án này?",
    projectDeleted: "Đã xóa dự án",
    projectCreated: "Đã tạo dự án",
    gridView: "Xem dạng lưới",
    listView: "Xem dạng danh sách",
    totalProjects: "Tổng dự án",
    activeProjects: "Đang hoạt động",
    completedProjects: "Hoàn thành",

    // Tasks
    tasks: "Công việc",
    createTask: "Tạo công việc",
    taskTitle: "Tiêu đề",
    taskDescription: "Mô tả",
    taskType: "Loại",
    story: "Story",
    bug: "Bug",
    task: "Task",
    epic: "Epic",
    priority: "Độ ưu tiên",
    highest: "Cao nhất",
    high: "Cao",
    medium: "Trung bình",
    low: "Thấp",
    lowest: "Thấp nhất",
    status: "Trạng thái",
    backlog: "Backlog",
    todo: "Cần làm",
    inProgress: "Đang làm",
    inReview: "Đang review",
    done: "Hoàn thành",
    assignee: "Người thực hiện",
    reporter: "Người báo cáo",
    dueDate: "Hạn chót",
    storyPoints: "Story Points",
    estimatedHours: "Giờ ước tính",
    labels: "Nhãn",
    noTasks: "Chưa có công việc",
    taskCreated: "Đã tạo công việc",
    taskUpdated: "Đã cập nhật công việc",
    taskDeleted: "Đã xóa công việc",
    overdue: "Quá hạn",

    // Task Handover
    handover: "Bàn giao",
    createHandover: "Tạo bàn giao",
    handoverTo: "Bàn giao cho",
    handoverReason: "Lý do bàn giao",
    handoverNotes: "Ghi chú bàn giao",
    pendingHandovers: "Bàn giao chờ xử lý",
    acceptHandover: "Chấp nhận bàn giao",
    rejectHandover: "Từ chối bàn giao",
    handoverAccepted: "Đã chấp nhận bàn giao",
    handoverRejected: "Đã từ chối bàn giao",
    handoverTask: "Bàn giao công việc",
    taskHandover: "Bàn giao công việc",
    handoverToRequired: "Bàn giao cho *",
    reasonForHandover: "Lý do bàn giao *",
    contextBackground: "Bối cảnh & Thông tin",
    workCompletedSoFar: "Công việc đã hoàn thành",
    pendingWork: "Công việc còn lại",
    currentBlockersIssues: "Vấn đề đang gặp",
    scheduleHandoverMeeting: "Lên lịch họp bàn giao",
    sendHandoverRequest: "Gửi yêu cầu bàn giao",
    selectTeamMember: "Chọn thành viên nhóm...",
    selectReason: "Chọn lý do...",
    vacationLeave: "Nghỉ phép/Nghỉ làm",
    workloadBalancing: "Phân bổ công việc",
    betterExpertiseMatch: "Chuyên gia phù hợp hơn",
    priorityChange: "Thay đổi ưu tiên",
    other: "Khác",
    provideImportantContext:
      "Cung cấp thông tin quan trọng về công việc này...",
    whatHasBeenDone: "Đã làm được gì rồi...",
    whatNeedsToBeDone: "Cần làm gì tiếp theo...",
    anyBlockersIssues: "Bất kỳ vấn đề nào người nhận cần biết...",
    handoverRequestSent: "Đã gửi yêu cầu bàn giao!",
    failedToCreateHandover: "Không thể tạo bàn giao",
    failedToLoadTask: "Không thể tải công việc",
    timeLoggedSuccessfully: "Đã ghi nhận thời gian",
    failedToLogTime: "Không thể ghi nhận thời gian",
    statusUpdated: "Đã cập nhật trạng thái",
    failedToUpdateStatus: "Không thể cập nhật trạng thái",
    loadingTask: "Đang tải công việc...",
    taskNotFound: "Không tìm thấy công việc",
    taskNotFoundDesc: "Công việc bạn đang tìm không tồn tại hoặc đã bị xóa.",
    goBack: "Quay lại",
    description: "Mô tả",
    noDescriptionProvided: "Chưa có mô tả",
    estimated: "Ước tính",
    actual: "Thực tế",
    progress: "Tiến độ",
    hours: "Giờ",
    whatDidYouWorkOn: "Bạn đã làm gì?",
    recentActivity: "Hoạt động gần đây",
    noDescription: "Không có mô tả",
    details: "Chi tiết",
    unassigned: "Chưa phân công",
    testing: "Đang test",
    blocked: "Bị chặn",
    critical: "Nghiêm trọng",
    taskBlocked: "Công việc bị chặn",
    taskBlockedDesc:
      "Công việc này đang bị chặn. Vui lòng giải quyết vấn đề để tiếp tục.",
    created: "Ngày tạo",

    // Time Tracking
    timeTracking: "Theo dõi thời gian",
    logTime: "Ghi nhận thời gian",
    hoursLogged: "Giờ đã ghi",
    timeLogDescription: "Mô tả công việc",
    totalTimeSpent: "Tổng thời gian",

    // Admin
    admin: "Quản trị",
    dashboard: "Bảng điều khiển",
    userManagement: "Quản lý người dùng",
    statistics: "Thống kê",
    totalUsers: "Tổng người dùng",
    totalPosts: "Tổng bài viết",
    searchUsers: "Tìm kiếm người dùng",
    searchProjects: "Tìm kiếm dự án",
    role: "Vai trò",
    user: "Người dùng",
    actions: "Hành động",
    view: "Xem",

    // Toast messages
    cannotAccessCamera: "Không thể truy cập camera/microphone",
    connectionFailed: "Kết nối thất bại",
    userOffline: "Người dùng không online",
    cannotShareScreen: "Không thể chia sẻ màn hình",
    stoppedSharing: "Đã dừng chia sẻ màn hình",
    startedSharing: "Đang chia sẻ màn hình",
    isSharingScreen: "đang chia sẻ màn hình",
    sharingLabel: "Đang chia sẻ",
    peopleConnecting: "người đang kết nối...",
    minutes: "phút",
    seconds: "giây",

    // Common errors
    cannotLoadData: "Không thể tải dữ liệu",
    cannotLoadGroup: "Không thể tải thông tin nhóm",
    cannotLoadMessages: "Không thể tải tin nhắn",
    cannotSendMessage: "Không thể gửi tin nhắn",
    cannotDeleteUser: "Không thể xóa người dùng",
    cannotUpdateRole: "Không thể cập nhật vai trò",
    cannotDeletePost: "Không thể xóa bài viết",

    // Success messages
    userDeleted: "Đã xóa người dùng",
    roleUpdated: "Đã cập nhật vai trò",
    messageSent: "Đã gửi tin nhắn",

    // Date/Time
    today: "Hôm nay",
    yesterday: "Hôm qua",
    daysAgo: "ngày trước",
    hoursAgo: "giờ trước",
    minutesAgo: "phút trước",
    justNow: "Vừa xong",

    // Misc
    online: "Trực tuyến",
    offline: "Ngoại tuyến",
    active: "Hoạt động",
    inactive: "Không hoạt động",
    all: "Tất cả",
    filter: "Lọc",
    sort: "Sắp xếp",
    search: "Tìm kiếm",
    noResults: "Không có kết quả",
    showMore: "Xem thêm",
    showLess: "Thu gọn",
    seeAll: "Xem tất cả",
    back: "Quay lại",
    next: "Tiếp theo",
    previous: "Trước đó",
    submit: "Gửi",
    send: "Gửi",
    save: "Lưu",
    update: "Cập nhật",
    create: "Tạo",
    add: "Thêm",
    remove: "Xóa",
    select: "Chọn",
    selected: "Đã chọn",
    selectAll: "Chọn tất cả",
    clear: "Xóa",
    reset: "Đặt lại",
    apply: "Áp dụng",
    completed: "Hoàn tất",
    yes: "Có",
    no: "Không",
    or: "hoặc",
    and: "và",
    of: "của",
    in: "trong",
    at: "lúc",
    by: "bởi",
    from: "từ",
    to: "đến",
    with: "với",
    for: "cho",

    // Form
    required: "Bắt buộc",
    optional: "Tùy chọn",
    enterValue: "Nhập giá trị",
    invalidEmail: "Email không hợp lệ",
    invalidPhone: "Số điện thoại không hợp lệ",
    passwordTooShort: "Mật khẩu quá ngắn",
    passwordsNotMatch: "Mật khẩu không khớp",

    // Empty states
    noData: "Không có dữ liệu",
    noItems: "Không có mục nào",
    emptyList: "Danh sách trống",

    // Projects page specific
    createProjectDescription:
      "Tạo dự án để tổ chức công việc, theo dõi tiến độ và cộng tác với nhóm của bạn sử dụng phương pháp Agile",
    tryAdjustingSearch: "Thử điều chỉnh từ khóa tìm kiếm",

    // Admin panel
    postManagement: "Quản lý bài viết",
    reported: "Bị báo cáo",
    deleteUser: "Xóa người dùng",
    confirmDeleteUser: "Bạn có chắc muốn xóa người dùng này?",
    banUser: "Cấm người dùng",
    unbanUser: "Bỏ cấm",
    banned: "Đã cấm",
    totalGroups: "Tổng nhóm",
    totalMessages: "Tổng tin nhắn",
    systemOverview: "Tổng quan hệ thống",
    quickStats: "Thống kê nhanh",
    manageUsers: "Quản lý người dùng",
    managePosts: "Quản lý bài viết",
    manageProjects: "Quản lý dự án",
    noUsersFound: "Không tìm thấy người dùng",
    noPostsFound: "Không tìm thấy bài viết",
    loadMore: "Tải thêm",
    refresh: "Làm mới",
    export: "Xuất",
    import: "Nhập",
    createdAt: "Ngày tạo",
    updatedAt: "Ngày cập nhật",
    content: "Nội dung",
    author: "Tác giả",
    likesCount: "Lượt thích",
    commentsCount: "Bình luận",
    sharesCount: "Lượt chia sẻ",
    viewPost: "Xem bài viết",
    deletePostConfirm: "Bạn có chắc muốn xóa bài viết này?",
    newUsersThisWeek: "Người dùng mới tuần này",
    newPostsThisWeek: "Bài viết mới tuần này",
    inLast7Days: "Trong 7 ngày gần đây",
    makeAdmin: "Cấp quyền Admin",
    makeUser: "Hạ xuống User",
    showing: "Hiển thị",
    users: "người dùng",
    page: "Trang",
  },
  en: {
    // Sidebar
    home: "Home",
    discover: "Discover",
    connections: "Connections",
    messages: "Messages",
    projects: "Projects",
    aiChat: "AI Chat",
    profile: "Profile",
    createPost: "Create Post",
    logout: "Logout",

    // Feed
    whatsHappening: "What's happening?",
    posts: "Posts",
    shares: "Shares",
    media: "Media",
    likes: "Likes",

    // Post actions
    like: "Like",
    comment: "Comment",
    share: "Share",
    sharePost: "Share Post",
    shareToProfile: "Share to Profile",
    addComment: "Add a comment...",
    writeComment: "Write a comment...",
    noComments: "No comments yet",
    loadingComments: "Loading comments...",
    commentAdded: "Comment added",
    commentDeleted: "Comment deleted",

    // Post management
    edit: "Edit",
    delete: "Delete",
    deletePost: "Delete Post",
    editPost: "Edit Post",
    deleting: "Deleting...",
    saving: "Saving...",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    postDeleted: "Post deleted",
    postUpdated: "Post updated",
    confirmDeletePost: "Are you sure you want to delete this post?",
    contentRequired: "Content is required",

    // Story
    createStory: "Create Story",
    deleteStory: "Delete Story",
    storyDeleted: "Story deleted",
    confirmDeleteStory: "Are you sure you want to delete this story?",
    text: "Text",
    photoVideo: "Photo/Video",

    // Connections
    followers: "Followers",
    following: "Following",
    pending: "Pending",
    connectionsLabel: "Connections",
    follow: "Follow",
    unfollow: "Unfollow",
    accept: "Accept",
    viewProfile: "View Profile",
    message: "Message",
    manageNetwork: "Manage your network and discover new connections",

    // Discover
    discoverPeople: "Discover People",
    connectWithPeople: "Connect with amazing people and grow your network",
    searchPlaceholder: "Search people by name, username, bio, or location...",

    // Messages
    talkToFriends: "Talk to friends or chat in groups",
    createGroup: "Create Group",
    groupName: "Group name",
    groups: "Groups",
    members: "members",
    noGroups: "No groups yet. Create one!",
    friends: "Friends",
    typeMessage: "Type a message...",
    postNotAdded: "Failed to add post",
    postAdded: "Post added",
    uploading: "Uploading...",
    confirmDeleteMessage: "Are you sure you want to delete this message?",
    messageDeleted: "Message deleted",

    // AI Chat
    newConversation: "New Conversation",
    noConversations: "No conversations yet",
    rename: "Rename",
    aiAssistant: "AI Assistant",
    chatting: "Chatting",
    aiWelcome: "Hello! I'm AI Assistant",
    aiDescription:
      "I can help you answer questions, write content, explain problems and much more. Let's start a conversation!",
    aiDisclaimer: "AI can make mistakes. Please verify important information.",

    // Create Post
    shareThoughts: "Share your thoughts with the world",
    publishPost: "Publish Post",

    // Profile
    editProfile: "Edit Profile",
    noPosts: "No posts yet",
    noSharedPosts: "No shared posts yet",
    joined: "Joined",
    addLocation: "Add location",
    addUsername: "Add a username",

    // Common
    loading: "Loading...",
    error: "Error",
    success: "Success",
    confirm: "Confirm",
    close: "Close",
    you: "You",
    new: "New",
    image: "Image",
    personal: "Personal",
    noMessages: "No messages yet",
    noGroupMessages: "No group messages yet",
    sponsored: "Sponsored",
    sharedAPost: "shared a post",
    addShareComment: "Add a comment to your share...",
    sharing: "Sharing...",
    postContent: "Post content...",

    // Login
    loginTitle: "More than just friends truly connect",
    loginSubtitle: "Connect with global community on PingUp.",
    usedByDevelopers: "Used by 12k+ developers",

    // Theme
    lightMode: "Light Mode",
    darkMode: "Dark Mode",

    // Language
    language: "Language",
    vietnamese: "Tiếng Việt",
    english: "English",

    // Video Call
    videoCall: "Video Call",
    audioCall: "Audio Call",
    groupCall: "Group Call",
    calling: "Calling...",
    connecting: "Connecting...",
    connected: "Connected",
    callEnded: "Call ended",
    callRejected: "Call rejected",
    callFailed: "Connection failed",
    endCall: "End call",
    mute: "Mute",
    unmute: "Unmute",
    turnOnCamera: "Turn on camera",
    turnOffCamera: "Turn off camera",
    shareScreen: "Share screen",
    stopSharing: "Stop sharing",
    screenSharing: "Screen sharing",
    waitingForOthers: "Waiting for others to join...",
    peopleInCall: "people in call",
    joinCall: "Join call",
    incomingCall: "Incoming call",
    acceptCall: "Accept",
    declineCall: "Decline",
    fullscreen: "Fullscreen",
    exitFullscreen: "Exit fullscreen",
    clickToExpand: "Click to expand",
    clickToClose: "Click anywhere to close",

    // Projects & Kanban
    projectManagement: "Project Management",
    createProject: "Create Project",
    createNewProject: "Create New Project",
    projectName: "Project Name",
    projectNamePlaceholder: "My Awesome Project",
    projectKey: "Project Key",
    projectKeyExample: "e.g., PROJ, DEV",
    projectKeyHint:
      "This will be used as prefix for task keys (e.g., PROJ-1, PROJ-2)",
    projectDescription: "Project Description",
    projectDescPlaceholder: "Describe your project...",
    projectCreatedSuccess: "Project created successfully!",
    failedToCreateProject: "Failed to create project",
    creating: "Creating...",
    noConnectionsAvailable: "No connections available. Add connections first.",
    methodology: "Methodology",
    scrum: "Scrum",
    kanban: "Kanban",
    waterfall: "Waterfall",
    startDate: "Start Date",
    endDate: "End Date",
    teamMembers: "Team Members",
    noProjects: "No projects yet",
    viewDetails: "View Details",
    deleteProject: "Delete Project",
    confirmDeleteProject: "Are you sure you want to delete this project?",
    projectDeleted: "Project deleted",
    projectCreated: "Project created",
    gridView: "Grid View",
    listView: "List View",
    totalProjects: "Total Projects",
    activeProjects: "Active",
    completedProjects: "Completed",

    // Tasks
    tasks: "Tasks",
    createTask: "Create Task",
    taskTitle: "Title",
    taskDescription: "Description",
    taskType: "Type",
    story: "Story",
    bug: "Bug",
    task: "Task",
    epic: "Epic",
    priority: "Priority",
    highest: "Highest",
    high: "High",
    medium: "Medium",
    low: "Low",
    lowest: "Lowest",
    status: "Status",
    backlog: "Backlog",
    todo: "To Do",
    inProgress: "In Progress",
    inReview: "In Review",
    done: "Done",
    assignee: "Assignee",
    reporter: "Reporter",
    dueDate: "Due Date",
    storyPoints: "Story Points",
    estimatedHours: "Estimated Hours",
    labels: "Labels",
    noTasks: "No tasks yet",
    taskCreated: "Task created",
    taskUpdated: "Task updated",
    taskDeleted: "Task deleted",
    overdue: "Overdue",

    // Task Handover
    handover: "Handover",
    createHandover: "Create Handover",
    handoverTo: "Handover to",
    handoverReason: "Reason",
    handoverNotes: "Notes",
    pendingHandovers: "Pending Handovers",
    acceptHandover: "Accept Handover",
    rejectHandover: "Reject Handover",
    handoverAccepted: "Handover accepted",
    handoverRejected: "Handover rejected",
    handoverTask: "Handover Task",
    taskHandover: "Task Handover",
    handoverToRequired: "Hand Over To *",
    reasonForHandover: "Reason for Handover *",
    contextBackground: "Context & Background",
    workCompletedSoFar: "Work Completed So Far",
    pendingWork: "Pending Work",
    currentBlockersIssues: "Current Blockers/Issues",
    scheduleHandoverMeeting: "Schedule Handover Meeting",
    sendHandoverRequest: "Send Handover Request",
    selectTeamMember: "Select team member...",
    selectReason: "Select reason...",
    vacationLeave: "Vacation/Leave",
    workloadBalancing: "Workload Balancing",
    betterExpertiseMatch: "Better Expertise Match",
    priorityChange: "Priority Change",
    other: "Other",
    provideImportantContext: "Provide important context about this task...",
    whatHasBeenDone: "What has been done already...",
    whatNeedsToBeDone: "What needs to be done next...",
    anyBlockersIssues: "Any blockers or issues the new assignee should know...",
    handoverRequestSent: "Task handover request sent!",
    failedToCreateHandover: "Failed to create handover",
    failedToLoadTask: "Failed to load task",
    timeLoggedSuccessfully: "Time logged successfully",
    failedToLogTime: "Failed to log time",
    failedToUpdateStatus: "Failed to update status",
    statusUpdated: "Status updated",
    loadingTask: "Loading task...",
    taskNotFound: "Task not found",
    taskNotFoundDesc:
      "The task you're looking for doesn't exist or has been deleted.",
    goBack: "Go Back",
    description: "Description",
    noDescriptionProvided: "No description provided",
    estimated: "Estimated",
    actual: "Actual",
    progress: "Progress",
    hours: "Hours",
    whatDidYouWorkOn: "What did you work on?",
    recentActivity: "Recent Activity",
    noDescription: "No description",
    details: "Details",
    unassigned: "Unassigned",
    testing: "Testing",
    blocked: "Blocked",
    critical: "Critical",
    taskBlocked: "Task Blocked",
    taskBlockedDesc:
      "This task is currently blocked. Please resolve blockers to continue working.",
    created: "Created",

    // Time Tracking
    timeTracking: "Time Tracking",
    logTime: "Log Time",
    hoursLogged: "Hours Logged",
    timeLogDescription: "Work Description",
    totalTimeSpent: "Total Time Spent",

    // Admin
    admin: "Admin",
    dashboard: "Dashboard",
    userManagement: "User Management",
    statistics: "Statistics",
    totalUsers: "Total Users",
    totalPosts: "Total Posts",
    searchUsers: "Search users",
    searchProjects: "Search projects",
    role: "Role",
    user: "User",
    actions: "Actions",
    view: "View",

    // Toast messages
    cannotAccessCamera: "Cannot access camera/microphone",
    connectionFailed: "Connection failed",
    userOffline: "User is offline",
    cannotShareScreen: "Cannot share screen",
    stoppedSharing: "Stopped screen sharing",
    startedSharing: "Screen sharing started",
    isSharingScreen: "is sharing screen",
    sharingLabel: "Sharing",
    peopleConnecting: "people connecting...",
    minutes: "minutes",
    seconds: "seconds",

    // Common errors
    cannotLoadData: "Cannot load data",
    cannotLoadGroup: "Cannot load group info",
    cannotLoadMessages: "Cannot load messages",
    cannotSendMessage: "Cannot send message",
    cannotDeleteUser: "Cannot delete user",
    cannotUpdateRole: "Cannot update role",
    cannotDeletePost: "Cannot delete post",

    // Success messages
    userDeleted: "User deleted",
    roleUpdated: "Role updated",
    messageSent: "Message sent",

    // Date/Time
    today: "Today",
    yesterday: "Yesterday",
    daysAgo: "days ago",
    hoursAgo: "hours ago",
    minutesAgo: "minutes ago",
    justNow: "Just now",

    // Misc
    online: "Online",
    offline: "Offline",
    active: "Active",
    inactive: "Inactive",
    all: "All",
    filter: "Filter",
    sort: "Sort",
    search: "Search",
    noResults: "No results",
    showMore: "Show more",
    showLess: "Show less",
    seeAll: "See all",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    send: "Send",
    save: "Save",
    update: "Update",
    create: "Create",
    add: "Add",
    remove: "Remove",
    select: "Select",
    selected: "Selected",
    selectAll: "Select all",
    clear: "Clear",
    reset: "Reset",
    apply: "Apply",
    completed: "Completed",
    yes: "Yes",
    no: "No",
    or: "or",
    and: "and",
    of: "of",
    in: "in",
    at: "at",
    by: "by",
    from: "from",
    to: "to",
    with: "with",
    for: "for",

    // Form
    required: "Required",
    optional: "Optional",
    enterValue: "Enter value",
    invalidEmail: "Invalid email",
    invalidPhone: "Invalid phone number",
    passwordTooShort: "Password too short",
    passwordsNotMatch: "Passwords do not match",

    // Empty states
    noData: "No data",
    noItems: "No items",
    emptyList: "Empty list",

    // Projects page specific
    createProjectDescription:
      "Create a project to organize tasks, track progress, and collaborate with your team using Agile methodology",
    tryAdjustingSearch: "Try adjusting your search query",

    // Admin panel
    postManagement: "Post Management",
    reported: "Reported",
    deleteUser: "Delete User",
    confirmDeleteUser: "Are you sure you want to delete this user?",
    banUser: "Ban User",
    unbanUser: "Unban",
    banned: "Banned",
    totalGroups: "Total Groups",
    totalMessages: "Total Messages",
    systemOverview: "System Overview",
    quickStats: "Quick Stats",
    manageUsers: "Manage Users",
    managePosts: "Manage Posts",
    manageProjects: "Manage Projects",
    noUsersFound: "No users found",
    noPostsFound: "No posts found",
    loadMore: "Load More",
    refresh: "Refresh",
    export: "Export",
    import: "Import",
    createdAt: "Created At",
    updatedAt: "Updated At",
    content: "Content",
    author: "Author",
    likesCount: "Likes",
    commentsCount: "Comments",
    sharesCount: "Shares",
    viewPost: "View Post",
    deletePostConfirm: "Are you sure you want to delete this post?",
    newUsersThisWeek: "New users this week",
    newPostsThisWeek: "New posts this week",
    inLast7Days: "In the last 7 days",
    makeAdmin: "Make Admin",
    makeUser: "Make User",
    showing: "Showing",
    users: "users",
    page: "Page",
  },
};
